version: '3'

services:
  database:
    restart: always
    image: postgres:latest
    volumes:
      - postgresql_data:/data

  restapi:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000 --settings=api.settings.local
    volumes:
      - ./api:/app
    ports:
      - 8999:8000
    links:
      - database

volumes:
  postgresql_data:
